# Nethermind with Lighthouse for Mainnet network
- id: sync-test-mainnet-nethermind-lighthouse
  name: Sync Test (Mainnet) - nethermind/lighthouse
  owner: ethpandaops
  repo: syncoor-tests
  workflow_id: syncoor.yaml
  ref: master
  labels:
    network: mainnet
    el-client: nethermind
    cl-client: lighthouse
  inputs:
    runs-on: '{"group": "synctest", "labels": "Disk4TB"}'
    run-timeout-minutes: "360"
    el-client: '"nethermind"'
    cl-client: '"lighthouse"'
    config: >-
      {
        "network": "mainnet",
        "consensus": {
          "syncType": "checkpoint",
          "nodeType": "fullnode",
          "checkpointSyncURL": "https://mainnet-checkpoint-sync.attestant.io",
          "images": {
            "lighthouse": "sigp/lighthouse:latest"
          }
        },
        "execution": {
          "images": {
            "nethermind": "nethermind/nethermind:latest"
          }
        }
      }
