# Nethermind combinations for Hoodi network
- id: sync-test-hoodi-nethermind-lighthouse
  name: Sync Test (Hoodi) - nethermind/lighthouse
  owner: ethpandaops
  repo: syncoor-tests
  workflow_id: syncoor.yaml
  ref: master
  labels:
    network: hoodi
    el-client: nethermind
    cl-client: lighthouse
  inputs:
    run-timeout-minutes: "1380"
    el-client: '"nethermind"'
    cl-client: '"lighthouse"'
    config: >-
      {
        "network": "hoodi",
        "consensus": {
          "syncType": "checkpoint",
          "nodeType": "fullnode",
          "images": {
            "lighthouse": "sigp/lighthouse:latest"
          }
        },
        "execution": {
          "images": {
            "nethermind": "nethermind/nethermind:latest"
          }
        }
      }

- id: sync-test-hoodi-nethermind-teku
  name: Sync Test (Hoodi) - nethermind/teku
  owner: ethpandaops
  repo: syncoor-tests
  workflow_id: syncoor.yaml
  ref: master
  labels:
    network: hoodi
    el-client: nethermind
    cl-client: teku
  inputs:
    run-timeout-minutes: "1380"
    el-client: '"nethermind"'
    cl-client: '"teku"'
    config: >-
      {
        "network": "hoodi",
        "consensus": {
          "syncType": "checkpoint",
          "nodeType": "fullnode",
          "images": {
            "teku": "consensys/teku:latest"
          }
        },
        "execution": {
          "images": {
            "nethermind": "nethermind/nethermind:latest"
          }
        }
      }

- id: sync-test-hoodi-nethermind-prysm
  name: Sync Test (Hoodi) - nethermind/prysm
  owner: ethpandaops
  repo: syncoor-tests
  workflow_id: syncoor.yaml
  ref: master
  labels:
    network: hoodi
    el-client: nethermind
    cl-client: prysm
  inputs:
    run-timeout-minutes: "1380"
    el-client: '"nethermind"'
    cl-client: '"prysm"'
    config: >-
      {
        "network": "hoodi",
        "consensus": {
          "syncType": "checkpoint",
          "nodeType": "fullnode",
          "images": {
            "prysm": "gcr.io/offchainlabs/prysm/beacon-chain:stable"
          }
        },
        "execution": {
          "images": {
            "nethermind": "nethermind/nethermind:latest"
          }
        }
      }

- id: sync-test-hoodi-nethermind-nimbus
  name: Sync Test (Hoodi) - nethermind/nimbus
  owner: ethpandaops
  repo: syncoor-tests
  workflow_id: syncoor.yaml
  ref: master
  labels:
    network: hoodi
    el-client: nethermind
    cl-client: nimbus
  inputs:
    run-timeout-minutes: "1380"
    el-client: '"nethermind"'
    cl-client: '"nimbus"'
    config: >-
      {
        "network": "hoodi",
        "consensus": {
          "syncType": "checkpoint",
          "nodeType": "fullnode",
          "images": {
            "nimbus": "statusim/nimbus-eth2:multiarch-latest"
          }
        },
        "execution": {
          "images": {
            "nethermind": "nethermind/nethermind:latest"
          }
        }
      }

- id: sync-test-hoodi-nethermind-lodestar
  name: Sync Test (Hoodi) - nethermind/lodestar
  owner: ethpandaops
  repo: syncoor-tests
  workflow_id: syncoor.yaml
  ref: master
  labels:
    network: hoodi
    el-client: nethermind
    cl-client: lodestar
  inputs:
    run-timeout-minutes: "1380"
    el-client: '"nethermind"'
    cl-client: '"lodestar"'
    config: >-
      {
        "network": "hoodi",
        "consensus": {
          "syncType": "checkpoint",
          "nodeType": "fullnode",
          "images": {
            "lodestar": "chainsafe/lodestar:latest"
          }
        },
        "execution": {
          "images": {
            "nethermind": "nethermind/nethermind:latest"
          }
        }
      }

- id: sync-test-hoodi-nethermind-grandine
  name: Sync Test (Hoodi) - nethermind/grandine
  owner: ethpandaops
  repo: syncoor-tests
  workflow_id: syncoor.yaml
  ref: master
  labels:
    network: hoodi
    el-client: nethermind
    cl-client: grandine
  inputs:
    run-timeout-minutes: "1380"
    el-client: '"nethermind"'
    cl-client: '"grandine"'
    config: >-
      {
        "network": "hoodi",
        "consensus": {
          "syncType": "checkpoint",
          "nodeType": "fullnode",
          "images": {
            "grandine": "sifrai/grandine:stable"
          }
        },
        "execution": {
          "images": {
            "nethermind": "nethermind/nethermind:latest"
          }
        }
      }
